import Head from 'next/head'

export default function Home() {

  return (
    <div className='h-screen overflow-y-scroll scrollbar-thin scrollbar-track-gray-900 scrollbar-thumb-secondary/80 scroll-smooth'>
      <Head>
        <title>Coral | Always There For You</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="./favicon.png" />      
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin=''/>
        <link
          href="https://fonts.googleapis.com/css2?family=Cabin&family=Poppins:wght@600&family=Lato:wght@400&display=swap"
          rel="stylesheet"/>
      </Head>

      <div className="h-screen w-screen flex flex-row items-center justify-center bg-[url('/form-texture.svg')] bg-cover p-4">
            <div className='flex flex-col w-full md:w-3/5 bg-white rounded-lg shadow-md text-center items-center p-8 md:p-16 space-y-6 overflow-y-scroll scrollbar-thin scrollbar-thumb-secondary scrollbar-track-transparent max-h-full'>
                <form className='flex flex-col space-y-3 w-3/5 mx-auto font-cabin text-sm items-center justify-center' action='/quiz/3'>
                  <h1 className='font-poppins text-4xl font-semibold'>Does worry or anxiety interfere with falling and/or staying asleep?</h1>
                  <div className='h-[4px] w-1/3 bg-gradient-to-r from-primary to-secondary self-center flex-shrink-0'></div>
                  
                  <input type="radio" className="checkbox-tools" name="choice" id="1" value="never"/>
                  <label className="for-checkbox-tools" htmlFor="1">Never</label>
                  <input type="radio" className="checkbox-tools" name="choice" id="2" value="rarely"/>
                  <label className="for-checkbox-tools" htmlFor="2">Rarely</label>
                  <input type="radio" className="checkbox-tools" name="choice" id="3" value="sometimes"/>
                  <label className="for-checkbox-tools" htmlFor="3">Sometimes</label>
                  <input type="radio" className="checkbox-tools" name="choice" id="4" value="often"/>
                  <label className="for-checkbox-tools" htmlFor="4">Often</label>
                  <input type="radio" className="checkbox-tools" name="choice" id="5" value="v_often"/>
                  <label className="for-checkbox-tools" htmlFor="5">Very Often</label>

                  <input
                    type="submit"
                    value="Next &gt;"
                    className="bg-primary/80 text-white font-semibold self-center cursor-pointer px-6 py-3 w-fit rounded-md hover:bg-primary transition transition-400 ease-in-out"
                  />
                </form>
                <hr className='border w-full'/>
                <a href='/'><img src='/home-text.png' alt='coral always there for you' className='w-full md:w-auto md:h-16'/></a>          
            </div>
        </div>


    </div>
  )
}
