import Head from 'next/head'
import { GetServerSideProps, NextPage } from "next";
import { useRouter } from "next/router";
import { LocalStorage } from "node-localstorage";

global.localStorage = new LocalStorage('./scratch'); 

function Quiz() {

  var user_l = localStorage.getItem('user')
  if (user_l) { 
    var user = JSON.parse(user_l);
  }

  const router = useRouter();

  const handleStart = async () => {
    router.push("/quiz/0");
  };

  return (
    <div className='h-screen overflow-y-scroll scrollbar-thin scrollbar-track-gray-900 scrollbar-thumb-secondary/80 scroll-smooth'>
      <Head>
        <title>Coral | Always There For You</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="./favicon.png" />      
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin=''/>
        <link
          href="https://fonts.googleapis.com/css2?family=Cabin&family=Poppins:wght@600&family=Lato:wght@400&display=swap"
          rel="stylesheet"/>
      </Head>

      <div className="h-screen w-screen flex flex-row items-center justify-center bg-[url('/form-texture.svg')] bg-cover p-4">
            <div className='flex flex-col w-full md:w-3/5 bg-white rounded-lg shadow-md text-center items-center justify-center p-8 md:p-16 space-y-6 overflow-y-scroll scrollbar-thin scrollbar-thumb-secondary scrollbar-track-transparent max-h-full'>
                <form className='flex flex-col space-y-3 w-3/5 mx-auto font-cabin text-sm items-center justify-center' onSubmit={handleStart}>
                  <h1 className='font-poppins text-4xl font-semibold'>Welcome {user.name}</h1>
                  <div className='h-[4px] w-1/3 bg-gradient-to-r from-primary to-secondary self-center flex-shrink-0'></div>

                  <input
                    type="submit"
                    value="Start the Quiz &gt;"
                    className="bg-primary/80 text-white font-semibold self-center cursor-pointer px-6 py-3 w-fit rounded-md hover:bg-primary transition transition-400 ease-in-out"
                  />
                </form>
                <hr className='border w-full'/>
                <a href='/'><img src='./home-text.png' alt='coral always there for you' className='w-full md:w-auto md:h-16'/></a>          
            </div>
        </div>


    </div>
  )
}
  
export default Quiz;