import Head from 'next/head'
import Navbar from '../components/Navbar'
import Footer from '../components/Footer'
import Profile from '../components/Profile'
import { grpData } from '../data/grpData'

export default function Dashboard() {

    const grps = grpData

    return (
        <div className='h-screen overflow-y-scroll scrollbar-thin scrollbar-track-gray-900 scrollbar-thumb-secondary/80 scroll-smooth'>
        <Head>
            <title>Coral | Always There For You</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="./favicon.png" />      
            <link rel="preconnect" href="https://fonts.googleapis.com" />
            <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin=''/>
            <link
            href="https://fonts.googleapis.com/css2?family=Cabin&family=Poppins:wght@600&family=Lato:wght@400&display=swap"
            rel="stylesheet"/>
        </Head>

        <Navbar logged />

        <div className='flex flex-col md:flex-row gap-8 px-6 md:px-36 pt-32 py-10' >

            <div className='w-1/2 flex flex-col gap-8'>

                <h1 className='font-poppins text-3xl font-semibold text-center'><span className='underline decoration-secondary'>Support Groups</span> Near You</h1>

                <div className='flex flex-col w-full space-y-6'>
                    {grps.map((card, i) => ( 
                        <Profile key={i} {...card} />
                    ))}
                </div>

                <a className='text-sm text-center text-[#79acc0] hover:text-[#5f94a9] transition duration-150 ease-in-out' href='dashboard'>&lt; Back to Home</a>

            </div>

            <div className='w-1/2'>
                <iframe src="https://www.google.com/maps/d/u/0/embed?mid=1qi1FdZtyTn8lNwLIr0u02-1WZ9OQt9U&ehbc=2E312F" className="w-full h-[33rem] rounded-lg"></iframe>
            </div>

        </div>

        <Footer logged/>

        </div>
    )
}
