import Head from 'next/head'
import Navbar from '../components/Navbar'
import Footer from '../components/Footer'
import {feedData} from '../data/feedData'

const video = {
  title: "5-Minute Meditation You Can Do Anywhere",
  desc: "In just 5 minutes you can reset your day in a positive way.",
  url: "https://www.youtube.com/embed/inpok4MKVLM",
  id: "001"
}

export default function Dashboard() {

  const feed = feedData

  return (
    <div className='h-screen overflow-y-scroll scrollbar-thin scrollbar-track-gray-900 scrollbar-thumb-secondary/80 scroll-smooth'>
      <Head>
        <title>Coral | Always There For You</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="./favicon.png" />      
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin=''/>
        <link
          href="https://fonts.googleapis.com/css2?family=Cabin&family=Poppins:wght@600&family=Lato:wght@400&display=swap"
          rel="stylesheet"/>
      </Head>

      <Navbar logged />

      <div className='flex flex-col gap-8 px-6 md:px-36 pt-32 py-10' >

        <h1 className='font-poppins text-3xl font-semibold text-center'>{video.title}</h1>

        

        <div className='flex flex-col w-full space-y-4 justify-center text-center items-center'>
          
            <iframe className='w-full md:w-4/5 h-96 rounded-lg' src={video.url} title={video.title} frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowFullScreen></iframe>

            <p className='text-gray-900 text-md font-cabin'>{video.desc}</p>

            <a className='text-sm text-[#79acc0] hover:text-[#5f94a9] transition duration-150 ease-in-out' href='dashboard'>&lt; Back to Home</a>

        </div>

      </div>

      <Footer logged/>

    </div>
  )
}
